name: Build & Test
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    name: test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Run cargo check
      run: cargo check
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests for compact feature
      run: cargo test --verbose --features compact
